# Enable or disable adding reviewers to pull requests
addReviewers: true

# Enable or disable adding assignees to pull requests
addAssignees: true

# List of GitHub usernames to be added as reviewers for pull requests
reviewers: 
  - Olaudo

# List of keywords to skip adding reviewers if they appear in the pull request
skipKeywords:
  - 2024

# Number of reviewers to be added to each pull request
# Set to 0 to add all available reviewers (default: 0)
numberOfReviewers: 0