updateDocsComment: >
  Thank you for submitting this pull request! It would be great if you could update the documentation to reflect your changes.

requestInfoReplyComment: >
  Could you please provide us with more details about this issue or pull request? We'd really appreciate it!

requestInfoLabelToAdd: request-more-info

newPRWelcomeComment: >
  Thank you for opening your first pull request here! We're excited to see your contribution.

firstPRMergeComment: >
  Congratulations on merging your first pull request here! 🎉 How awesome is that!

newIssueWelcomeComment: >
  Thank you for reporting this issue. I will review it and respond shortly!